# group vars
---

verbose: true
zram_ratio: 0.95

containers: true
containers_path: '/mnt/containers'

cert_enabled: true

server_count: 2

assetto_user: assetto
assetto_uid: 1210
assetto_group: assetto
assetto_gid: 1210

app_name: ac
app_port: 8772


# plugins
simview_receive_port: 130
stracker_proxy_plugin_local_port: 142
stracker_proxy_plugin_port: 141

# from acmanager defaults
upnp_enabled: 'false'
cmwelcome_enable: 1
lobby_port_prefix: 95
udp_port_prefix: 96
tcp_port_prefix: 96  # 97
plugin_udp_address: '127.0.0.1'
plugin_udp_local_port_prefix: 12
plugin_udp_port_prefix: 11

acmanager_path: '/usr/local/sbin/acmanager'
acserver_path: '/usr/local/sbin/acserver'
steamcmd_path: '/usr/local/sbin/steamcmd'
nginx_path: '/usr/share/nginx/html'

# systemd
systemd_single: server-manager.service
systemd_multi: multi-server-manager.service

# daily backups
backup_hours: '4'
backup_path: '/home/{{ assetto_user }}/backups'

# kmr
store_path: "{{ acmanager_path }}/shared_store.json"
kmr_web_stats_port_prefix: 85

# discord
discord_enabled: false
discord_url: 'https://discord.gg'

# donations
donate_paypal: false
paypal_link: 'https://www.paypal.com'
donate_buycoffee: false
buycoffee_link: 'https://www.buymeacoffee.com'
donate_patreon: false
patreon_link: 'http://patreon.com'
