# group vars
---

assetto_user: assetto
assetto_uid: 1210
assetto_group: assetto
assetto_gid: 1210

app_name: ac
app_port: 8772

acmanager_path: '/usr/local/sbin/acmanager'
acserver_path: '/usr/local/sbin/acserver'
steamcmd_path: '/usr/local/sbin/steamcmd'
nginx_path: '/usr/share/nginx/html'

kmr_welcome_message: '    ""'

# donations
donate_paypal: false
paypal_link: ''

donate_buycoffee: false
buycoffee_link: ''
