# configure redirect domains in nginx

---
# remove nginx conf file entry for fqdn if file exists

- name: install http redirect to https html
  ansible.builtin.template:
    src: redirect.html.j2
    dest: "{{ nginx_path }}/{{ site_fqdn }}/html/index.html"
    owner: nginx
    group: nginx
    mode: '0640'
  when: cert_enabled

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: redirect.changed
