# acmanager acserver nginx vars
---

assetto_user: assetto
assetto_uid: 1210
assetto_group: assetto
assetto_gid: 1210

app_name: acsm
app_port: 8772

install_kmr: true   # this is a bool
kmrEnabled: 'true'  # this is a string
acmanagerMonitoring: false

backup_hours: "4"
backup_path: "/home/{{ assetto_user }}/backups"

acmanager_path: "/usr/local/sbin/acmanager"
acserver_path: "/usr/local/sbin/acserver"
steamcmd_path: "/usr/local/sbin/steamcmd"

nginx_path: "/usr/share/nginx/html"

systemd_single: server-manager.service
systemd_multi: multi-server-manager.service

disable_plugins: false
performance_mode: false
scan_content_folder: true
lua_enabled: false

url_prefix: "{{ 'https' if cert_enabled else 'http' }}"

upnp_enabled: 'false'

acmanagerZip: acsm_v2.*_linux-amd64.zip
acmanagerZipArm32: acsm_v2.*_linux-arm32.zip

acmanagerSessionStoreType: filesystem
acmanagerSessionStorePath: "{{ acmanager_path }}/session-store"
acmanagerSessionMaxAge: 720h  # 720h is the default

acmanagerTLSEnabled: false
acmanagerCertPath: "/etc/letsencrypt/live/{{ site_fqdn }}/cert.pem"
acmanagerKeyPath: "/etc/letsencrypt/live/{{ site_fqdn }}/privkey.pem"

acmanagerStoreType: json
acmanagerStorePath: "{{ acmanager_path }}/shared_store.json"
acmanagerStoreSharedDataPath: "{{ acmanager_path }}/shared_store.json"
acmanagerStoreScheduledEventCheckLoop: 0s  # 0s is the default
acmanagerMapRefreshInterval_ms: 500  # 500 is the default

acmanagerPersistSessionResults: false  # the default is false

acmanagerIndexLaps: true
acmanagerIndexCrashes: false

acmanagerRecaptchaSiteKey: ""
acmanagerRecaptchaSecretKey: ""

httpHostname: 0.0.0.0:8772

steamcmdForceUpdate: false

# multiserver
#lobby_port_prefix: 95
#udp_port_prefix: 96
#tcp_port_prefix: 97

enableContentManager: 1


  # # kmr
  # kmrZip: kmr_*.zip
  # live_track_view: 1
  #   #kmrConfig: kissmyrank_options.json
  # 
  # web_stats_interface: 1
  # right_to_be_forgotten: 1
  # show_race_control_link: 1
  # cut_lines_enabled: 0

# multi-server ACSM
#plugin_udp_local_port_prefix: 12
plugin_udp_address: '127.0.0.1'
plugin_udp_port_prefix: 11
kmr_web_auth_port: '001'
  #kmr_ac_app_link_prefix: 13
  #kmr_web_stats_port_prefix: 77
kmr_database_port: 8701

  ## stracker
  #strConfig: stracker_options.json
  #install_stracker: false

# stand alone ACSM server
UDPPluginLocalPort: 12000
UDPPluginAddress: '127.0.0.1:12001'
