# simview vars
---

app_user: simview
app_uid: 1212
app_group: simview
app_gid: 1212

app_name: simview
app_port: 9898
simview_websocket_port_prefix: 122

app_path: '/usr/local/sbin/{{ app_name }}'
simview_cert_path: '/usr/local/sbin/{{ app_name }}/certs'

root_mysql_pw: 'root'
simviewdb_pass: 'simview'
