# update playbook
---
### all hosts ###

- hosts: all
  gather_facts: true
  become: true

  roles:
    - common
    - sshd

  handlers:
    - name: restart system
      ansible.builtin.reboot:

    - name: reload network
      ansible.builtin.systemd:
        name: network
        state: reloaded
