# ansible-galaxy install -r requirements.yml
---
- src: community.general
- src: ansible.posix
- src: community.crypto
- src: community.mysql

# /Users/Ian/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
ansible.posix        1.5.1  
community.crypto     2.10.0 
community.general    6.3.0  
community.mysql      3.7.2  
community.postgresql 3.2.0  
containers.podman    1.9.3  
