# ansible-galaxy collection install -r requirements.yml
---
collections:
  - name: community.general
    version: 6.3.0

  - name: ansible.posix
    version: 1.5.1

  - name: community.crypto
    version: 2.10.0

  - name: community.mysql
    version: 3.7.2

  - name: community.postgresql
    version: 3.2.0

  - name: containers.podman
    version: 1.9.3
