# Master Playbook
---
### all hosts ###

- hosts: all
  gather_facts: true
  become: true

  roles:
    - common
    - sshd
    - zram

  handlers:
    - name: restart system
      ansible.builtin.reboot:

    - name: reload network
      ansible.builtin.systemd:
        name: network
        state: reloaded

### west server ###

- hosts: west
  become: true

  roles:
    - acsm_backup

### east server ###

- hosts: east
  become: true

  roles:
    - base-nginx
    - steamcmd
    - acmanager
    #    - certbot renew script
    #    - postfix

  handlers:
    - name: reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded

    - name: restart acsm
      ansible.builtin.systemd:
        name: server-manager
        state: restarted

    - name: restart acsm multi
      ansible.builtin.systemd:
        name: multi-server-manager
        state: restarted
