# custom error and index pages
---
- name: add custom error page dirs
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: u=rwX,g=rX,o=rX
    state: directory
  with_items:
    - "{{ nginx_path }}/error_pages"
    - "{{ nginx_path }}/error_pages/401"
    - "{{ nginx_path }}/error_pages/404"
    - "{{ nginx_path }}/error_pages/50x"

- name: add custom 401 error page
  ansible.builtin.template:
    src: 401-error.html.j2
    dest: "{{ nginx_path }}/error_pages/401/401-error.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0640'

- name: add custom 404 error page
  ansible.builtin.template:
    src: 404-error.html.j2
    dest: "{{ nginx_path }}/error_pages/404/404-error.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0640'

- name: add custom 50x error page
  ansible.builtin.template:
    src: 50x-error.html.j2
    dest: "{{ nginx_path }}/error_pages/50x/50x-error.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0640'

- name: add custom maintenace page
  ansible.builtin.template:
    src: maintenance_page.html.j2
    dest: "{{ nginx_path }}/maintenance_page.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0640'

- name: add maintenance page config file
  ansible.builtin.template:
    src: default_server.conf.j2
    dest: "/etc/nginx/conf.d/default_server.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0640'

- name: replace nginx defualt index page
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ nginx_path }}/index.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: u=rwX,g=rX,o=rX

- name: add robots.txt
  ansible.builtin.copy:
    src: robots.txt
    dest: "{{ nginx_path }}/robots.txt"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: u=rwX,g=rX,o=rX

- name: add domain http conf
  ansible.builtin.template:
    src: domain_http.conf.j2
    dest: "{{ nginx_conf }}/{{ site_fqdn }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: u=rwX,g=rX,o=rX
  when: not cert_enabled

- name: add domain https conf
  ansible.builtin.template:
    src: domain_https.conf.j2
    dest: "{{ nginx_conf }}/{{ site_fqdn }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: u=rwX,g=rX,o=rX
  when: cert_enabled
