# custom error and index pages
#
---
- name: add custom error pages
  ansible.builtin.copy:
    src: "error_pages"
    dest: "{{ nginx_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: u=rwX,g=rX,o=rX
  register: build_debug

- name: debug
  ansible.builtin.debug:
    msg: "{{ build_debug }}"
  when: verbose

- name: add nginx domain subfolder
  ansible.builtin.file:
    path: "{{ nginx_path }}/{{ app_name }}.{{ site_fqdn }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: u=rwX,g=rX,o=rX
    state: directory

- name: add custom index page
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ nginx_path }}/{{ app_name }}.{{ site_fqdn }}/index.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: u=rwX,g=rX,o=rX
  register: build_debug

- name: debug
  ansible.builtin.debug:
    msg: "{{ build_debug }}"
  when: verbose

- name: add robots.txt
  ansible.builtin.copy:
    src: robots.txt
    dest: "{{ nginx_path }}/robots.txt"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: u=rwX,g=rX,o=rX

- name: add domain http conf
  ansible.builtin.template:
    src: domain_http.conf.j2
    dest: "{{ nginx_conf }}/{{ app_name }}.{{ site_fqdn }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: u=rwX,g=rX,o=rX
      #   when: not cert_enabled
  register: build_debug

- name: debug
  ansible.builtin.debug:
    msg: "{{ build_debug }}"
  when: verbose

    # - name: add domain https conf
    #   ansible.builtin.template:
    #     src: domain_https.conf.j2
    #     dest: "{{ nginx_conf }}/{{ app_name }}.{{ site_fqdn }}.conf"
    #     owner: "{{ nginx_user }}"
    #     group: "{{ nginx_group }}"
    #     mode: u=rwX,g=rX,o=rX
    #   when: cert_enabled
    #   register: build_debug
    #
    # - name: debug
    #   ansible.builtin.debug:
    #     msg: "{{ build_debug }}"
    #   when: verbose
