# firewalld for kmr
---
- name: debug
  ansible.builtin.debug:
    msg: "{{ kmr_web_stats_port_prefix }}{{ item }}/tcp"
  with_sequence: start=0 end={{ server_count -1 }} format=%02x

- name: open KMR web stats TCP
  ansible.builtin.firewalld:
    port: "{{ kmr_web_stats_port_prefix }}{{ item }}/tcp"
    state: enabled
  with_sequence: start=0 end={{ server_count -1 }} format=%02x

    ### these are internal plugin ports
    # - name: open KMR plugin tcp
    #   ansible.builtin.firewalld:
    #     port: "{{ kmr_plugin_port_prefix }}0{{ item }}/tcp"
    #     state: enabled
    #   with_sequence: start=0 end={{ server_count -1 }} format=%02x
    # 
    # - name: open KMR plugin udp
    #   ansible.builtin.firewalld:
    #     port: "{{ kmr_plugin_port_prefix }}0{{ item }}/udp"
    #     state: enabled
    #   with_sequence: start=0 end={{ server_count -1 }} format=%02x
    
- name: open KMR app link UDP
  ansible.builtin.firewalld:
    port: "{{ kmr_ac_app_link_prefix }}{{ item }}/udp"
    state: enabled
  with_sequence: start=0 end={{ server_count -1 }} format=%02x
