# daily backups
---
- name: create backup directory
  ansible.builtin.file:
    path: "{{ backup_path }}"
    state: directory
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0750'

- name: add helper script for backups
  ansible.builtin.template:
    src: daily_backup.sh.j2
    dest: "{{ acmanager_path }}/daily_backup.sh"
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0740'

- name: create daily backup acsm log file
  ansible.builtin.file:
    state: touch
    path: /var/log/daily_backup_acsm.log
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0644'

- name: add cron job for backup script
  become_user: "{{ assetto_user }}"
  ansible.builtin.cron:
    name: daily acsm backup
    minute: "15"
    hour: "{{ backup_hours }}"
    job: "{{ acmanager_path }}/daily_backup.sh >> /var/log/daily_backup_acsm.log 2>&1"
