# install simview
---
- name: install dependencies
  ansible.builtin.package:
    pkg: mysql-server
    state: latest

- name: create isolation user and group. Enable linger
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user.yml
  vars:
    user: "{{ app_user }}"
    uid: "{{ app_uid }}"
    group: "{{ app_group }}"
    gid: "{{ app_gid }}"
    comment: "{{ app_name }} app account"

- name: create app path "{{ app_path }}"
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
  register: simview_path_state
