# sysctl network memory values
---
- name: add sysctl ipv4 network memory values
  ansible.builtin.template:
    src: acmanager_ipv4_settings.conf.j2
    dest: /etc/sysctl.d/99_acmanager_ipv4_settings.conf
    mode: '0640'
  register: sysctl_settings

- name: reload sysctl if new values set
  ansible.builtin.command:
    cmd: sysctl --load /etc/sysctl.d/99_acmanager_ipv4_settings.conf
  when: sysctl_settings.changed
