# fail2ban main.yml
---
- name: install fail2ban
  ansible.builtin.package:
    name:
      - fail2ban
    state: latest

- name: add jail.local template
  ansible.builtin.template:
    src: jail_local.j2
    dest: "{{ app_path }}/jail.local"
    owner: root
    group: root
    mode: '0644'
  register: jail_local_status

- name: enable and restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: restarted
  when: jail_local_status.changed
