# firewalld for AC Server Manager
---

- name: open http port
  ansible.builtin.firewalld:
    port: 80/tcp
    state: enabled

- name: open https port
  ansible.builtin.firewalld:
    port: 443/tcp
    state: enabled
  when: cert_enabled

- name: open dev http port 8772/tcp if certs are disabled
  ansible.builtin.firewalld:
    port: 8772/tcp
    state: enabled
  when: not cert_enabled

- name: open lobby http ports
  ansible.builtin.firewalld:
    port: "{{ lobby_port_prefix }}{{ item }}/tcp"
    state: enabled
  with_sequence: start=0 end={{ server_count -1 }} format=%02x

- name: open udp ports
  ansible.builtin.firewalld:
    port: "{{ udp_port_prefix }}{{ item }}/udp"
    state: enabled
  with_sequence: start=0 end={{ server_count -1 }} format=%02x

- name: open tcp ports
  ansible.builtin.firewalld:
    port: "{{ tcp_port_prefix }}{{ item }}/tcp"
    state: enabled
  with_sequence: start=0 end={{ server_count -1 }} format=%02x

- name: open KMR web interface TCP ports
  ansible.builtin.firewalld:
    port: "{{ kmr_web_stats_port_prefix }}{{ item }}/tcp"
    state: enabled
  with_sequence: start=0 end={{ server_count -1 }} format=%02x



### STRACKER NOT IMPLEMENTED YET ###

# - name: open 50041/tcp for stracker http #global
#   ansible.builtin.firewalld:
#     port: 50041/tcp
#     state: enabled
#
# - name: open 50042/tcp for stracker data #1
#   ansible.builtin.firewalld:
#     port: 50042/tcp
#     state: enabled
#
# - name: open 50043/tcp for stracker data #2
#   ansible.builtin.firewalld:
#     port: 50043/tcp
#     state: enabled


    ### commnted out 7-14-2022 as these are local plugin addresses ###
    # - name: open ACSM plugin TCP ports
    #   ansible.builtin.firewalld:
    #     port: "{{ plugin_udp_port_prefix }}0{{ item }}/tcp"
    #     state: enabled
    #   with_sequence: start=0 end={{ server_count -1 }} format=%02x
    #
    # - name: open ACSM plugin UDP ports
    #   ansible.builtin.firewalld:
    #     port: "{{ plugin_udp_port_prefix }}0{{ item }}/udp"
    #     state: enabled
    #   with_sequence: start=0 end={{ server_count -1 }} format=%02x

    ### commented out 7-14-2022 as they are local ports for plugins to talk ###
    # - name: open KMR admin console TCP ports
    #   ansible.builtin.firewalld:
    #     port: "{{ plugin_udp_local_port_prefix }}0{{ item }}/tcp"
    #     state: enabled
    #   with_sequence: start=0 end={{ server_count -1 }} format=%02x
    #
    # - name: open KMR admin console UDP ports
    #   ansible.builtin.firewalld:
    #     port: "{{ plugin_udp_local_port_prefix }}0{{ item }}/udp"
    #     state: enabled
    #   with_sequence: start=0 end={{ server_count -1 }} format=%02x

    ### commented out 7-14-2022 as I'm not sure anyone uses AC app link client side ###
    # - name: open KMR ac app link UDP ports
    #   ansible.builtin.firewalld:
    #     port: "{{ kmr_ac_app_link_prefix }}0{{ item }}/udp"
    #     state: enabled
    #   with_sequence: start=0 end={{ server_count -1 }} format=%02x
