# common role, all systems
---
- name: print facts
  ansible.builtin.debug:
    msg:
      - "nodename: {{ansible_facts.nodename}}"
      - "os_family: {{ansible_os_family}}"
  when: verbose

- name: enable EPEL on Fedora 8 systems
  ansible.builtin.import_tasks: rhel8epel.yml
  when: ansible_distribution_major_version == "8" and
   (ansible_distribution == "CentOS" or ansible_distribution == 'RedHat')

- name: install utility packages
  ansible.builtin.import_tasks: install_packages.yml

- name: add admin users
  ansible.builtin.import_tasks: admin_users.yml

- name: set firewalld
  ansible.builtin.import_tasks: firewalld.yml

- name: set selinux
  ansible.builtin.import_tasks: selinux.yml

- name: tweak RPi2B nic name
  ansible.builtin.import_tasks: rpi2b.yml

- name: force systemd to reread configs
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
