# firewalld for stracker
---
- name: open stracker web listen address
  ansible.builtin.firewalld:
    port: "50041/tcp"
    state: enabled

- name: open ports for plugin
  ansible.builtin.firewalld:
    port: "{{ udp_port_prefix }}{{ intvalue | string }}/tcp"
    state: enabled
  vars:
    intvalue: "{{ 42 + item | int }}"
  with_sequence: start=0 end={{ server_count -1 }} format=%02x
