# backup acserver and acmanager
---
- name: set timestamp for backup
  ansible.builtin.command: 'date +%Y%m%d'
  register: timestamp

- name: create backup directory
  ansible.builtin.file:
    path: "{{ backup_path }}"
    state: directory
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0750'

- name: backup current AC Server Manager install
  ansible.builtin.archive:
    path:
      - "{{ acserver_path }}/*"
      - "{{ acmanager_path }}/*"
    exclude_path:
      - "{{ acserver_path }}/content"
      - "{{ acmanager_path }}/*.zip"
      - "{{ acmanager_path }}/ACSM.License"
    dest: "{{ backup_path }}/{{ acsm_version.stdout }}_{{ timestamp.stdout }}.zip"
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0644'
    format: zip

- name: backup game content; cars, tracks, weather
  ansible.builtin.archive:
    path: "{{ acserver_path }}/content"
    dest: "{{ backup_path }}/acsm_content.zip"
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0644'
    format: zip
