# backup acserver and acmanager
---
- name: set timestamp for backup
  ansible.builtin.command: 'date +%Y%m%d.%H%M%S'
  register: timestamp

- name: backup current AC Server Manager install
  ansible.builtin.archive:
    path:
      - "{{ acserverPath }}/*"
      - "{{ acmanagerPath }}/*"
    exclude_path:
      - "{{ acserverPath }}/content"
      - "{{ acmanagerPath }}/*.zip"
      - "{{ acmanagerPath }}/ACSM.License"
    dest: "{{ backup_path }}/{{ acsm_version.stdout }}_{{ timestamp.stdout }}.zip"
    owner: "{{ assettouser }}"
    group: "{{ assettogroup }}"
    mode: '0644'
    format: zip

- name: backup game content; cars, tracks, weather
  ansible.builtin.archive:
    path: "{{ acserverPath }}/content"
    dest: "{{ backup_path }}/acsm_content.zip"
    owner: "{{ assettouser }}"
    group: "{{ assettogroup }}"
    mode: '0644'
    format: zip
