# backup acserver and acmanager
---
- name: create backup directory
  ansible.builtin.file:
    path: "{{ backup_path }}"
    state: directory
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0750'

- name: if backup directory exists, update file ownership for any files in directory
  ansible.builtin.file:
    path: "{{ backup_path }}"
    state: directory
    recurse: true
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"

- name: add helper script for backups
  ansible.builtin.template:
    src: get_version.sh.j2
    dest: "{{ acmanager_path }}/get_version.sh"
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0740'

- name: add backup script
  ansible.builtin.template:
    src: daily_backup.sh.j2
    dest: "{{ acmanager_path }}/daily_backup.sh"
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0740'

- name: add backup restore script
  ansible.builtin.template:
    src: 'restore_acsm.sh.j2'
    dest: "{{ backup_path }}/acsm_restore.sh"
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0740'

- name: create daily backup acsm log file
  ansible.builtin.file:
    state: touch
    path: /var/log/daily_backup_acsm.log
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0644'

- name: add cron job for backup script
  become_user: "{{ assetto_user }}"
  ansible.builtin.cron:
    name: daily acsm backup
    minute: "15"
    hour: "{{ backup_hours }}"
    job: "{{ acmanager_path }}/daily_backup.sh >> /var/log/daily_backup_acsm.log 2>&1"

  # why? ansible.archive will not keep symlinks when saving to zip
- name: run backup script on current AC server install
  become_user: "{{ assetto_user }}"
  ansible.builtin.command:
    cmd: '{{ acmanager_path }}/daily_backup.sh'
  when: not acmanager_path_state.changed
  register: backup_script_state

    #- name: output of backup script
    #  ansible.builtin.debug:
    #    msg: "{{ backup_script_state }}"
