# pull latest archive of game content and shared data
---
- name: add content
  ansible.builtin.unarchive:
    src: "{{ files_server }}/acsm_content.zip"
    dest: "{{ acserverPath }}/"
    owner: "{{ assettouser }}"
    group: "{{ assettouser }}"
    mode: '0755'
    remote_src: true
  ignore_errors: true

- name: add custom races
  ansible.builtin.unarchive:
    src: "{{ files_server }}/acsm_shared_data.zip"
    dest: "{{ acmanagerStorePath }}/"
    owner: "{{ assettouser }}"
    group: "{{ assettouser }}"
    mode: '0755'
    remote_src: true
  ignore_errors: true
