# CSS mods
---

- name: insert CSS in AC server manager
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regex: '^  "CustomCSS": '
    line: '  "CustomCSS": ".bg-primary, .btn-primary, .badge-primary {\r\n  background-color: #748688 !important;\r\n  border-color: #3a4344 !important;\r\n}",'
    state: present

- name: insert OGImage in AC server manager
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regex: '^  "OGImage": '
    line: '  "OGImage": "https://www.{{ site_fqdn }}/{{ server_icon_small }}",'
    state: present

- name: insert Favicon in AC server manager
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regex: '^  "Favicon": '
    line: '  "Favicon": "https://www.{{ site_fqdn }}/{{ server_icon_small }}",'
    state: present

- name: check if AC multi manager is installed
  ansible.builtin.stat:
    path: "{{ acmanager_path }}/servers/SERVER_00/store.json/server_options.json"
  register: acmm_installed

- name: insert CSS in AC multi manager
  ansible.builtin.lineinfile:
    dest: "{{ acmanager_path }}/servers/SERVER_0{{ item }}/store.json/server_options.json"
    regex: '^  "CustomCSS": '
    line: '  "CustomCSS": ".bg-primary, .btn-primary, .badge-primary {\r\n  background-color: #748688 !important;\r\n  border-color: #3a4344 !important;\r\n}",'
    state: present
  with_sequence: start=0 end={{ server_count -1 }}
  when: acmm_installed.stat.exists

- name: insert OGImage in AC multi manager
  ansible.builtin.lineinfile:
    dest: "{{ acmanager_path }}/servers/SERVER_0{{ item }}/store.json/server_options.json"
    regex: '^  "OGImage": '
    line: '  "OGImage": "https://www.{{ site_fqdn }}/{{ server_icon_small }}",'
    state: present
  with_sequence: start=0 end={{ server_count -1 }}
  when: acmm_installed.stat.exists

- name: insert Favicon in AC multi manager
  ansible.builtin.lineinfile:
    dest: "{{ acmanager_path }}/servers/SERVER_0{{ item }}/store.json/server_options.json"
    regex: '^  "Favicon": '
    line: '  "Favicon": "https://www.{{ site_fqdn }}/{{ server_icon_small }}",'
    state: present
  with_sequence: start=0 end={{ server_count -1 }}
  when: acmm_installed.stat.exists

