# lobby messages
---
- name: check if AC multi manager is installed
  ansible.builtin.stat:
    path: "{{ acmanager_path }}/servers/SERVER_00/"
  register: acmm_installed

- name: insert motd message for single server
  ansible.builtin.template:
    src: motd.j2
    dest: "{{ acserver_path }}/motd.txt"
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0644'
  when: server_count == 1

- name: insert motd message for multi servers
  ansible.builtin.template:
    src: motd.j2
    dest: "{{ acmanager_path }}/servers/SERVER_{{ item }}/assetto/motd.txt"
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0644'
  with_sequence: start=0 end={{ server_count -1 }} format=%02x
  when: server_count > 1 and acmm_installed.stat.exists

- name: insert join message for single server
  ansible.builtin.lineinfile:
    dest: "{{ store_path }}/server_options.json"
    regex: '^  "ServerJoinMessage": '
    line: '  "ServerJoinMessage": " ",'
    state: present

- name: insert join message for multi servers
  ansible.builtin.lineinfile:
    dest: "{{ acmanager_path }}/servers/SERVER_{{ item }}/store.json/server_options.json"
    regex: '^  "ServerJoinMessage": '
    line: '  "ServerJoinMessage": " ",'
    state: present
  with_sequence: start=0 end={{ server_count -1 }} format=%02x
  when: server_count > 1 and acmm_installed.stat.exists

- name: pull custom cm welcome message
  ansible.builtin.get_url:
    url: "{{ files_server }}/welcome_{{ site_fqdn }}.txt"
    dest: /tmp/cm_welcome.txt
    owner: root
    group: root
    mode: '0440'
  register: custom_cm_welcome_status

- name: if no custom cm welcome, use default
  ansible.builtin.copy:
    src: cm_welcome.txt
    dest: /tmp/cm_welcome.txt
    owner: root
    group: root
    mode: '0440'
  when: custom_cm_welcome_status.failed

- name: slurp cm welcome message
  ansible.builtin.slurp:
    src: /tmp/cm_welcome.txt
  register: cm_welcome_slurp

- name: insert content manger welcome message
  ansible.builtin.lineinfile:
    dest: "{{ store_path }}/server_options.json"
    regexp: '^  "ContentManagerWelcomeMessage": '
    line: "{{ cm_welcome_slurp['content'] | b64decode }}"
    state: present

- name: insert content manger welcome messag multi serverse
  ansible.builtin.lineinfile:
    dest: "{{ acmanager_path }}/servers/SERVER_{{ item }}/store.json/server_options.json"
    regexp: '^  "ContentManagerWelcomeMessage": '
    line: "{{ cm_welcome_slurp['content'] | b64decode }}"
    state: present
  with_sequence: start=0 end={{ server_count -1 }} format=%02x
  when: server_count > 1 and acmm_installed.stat.exists
