# restart and wait handler
---

- name: restart multi-server-manager service
  ansible.builtin.systemd:
    name: "{{ acMultiServerManagerSystemd }}"
    state: restarted

- name: wait for multi-server-manager to settle
  ansible.builtin.uri:
    url: "http://127.0.0.1:8772/login"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 720 # 720 * 5 = 1 hour
  delay: 5
