# single server options
---
- name: set UPnP state
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regex: '^  "UPnP": true,$'
    line: '  "UPnP": {{ upnp_enabled }},'
    state: present

- name: update name for server
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regex: '^  "Name": '
    line: '  "Name": "{{ gameServerShort }}00 | {{ gameServerName }}",'
    state: present

- name: Do not connect online to AC servers when testing
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regex: '^  "RegisterToLobby": 1,$'
    line: '  "RegisterToLobby": 0,'
    state: present
  when: not cert_enabled

- name: set lobby http port
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regex: '^  "HTTPPort": '
    line: '  "HTTPPort": {{ lobby_port_prefix }}00,'

- name: set number of threads to system thread count
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regex: '^  "NumberOfThreads": 2,$'
    line: '  "NumberOfThreads": {{ ansible_processor_nproc }},'  # set cores
  when: ansible_processor_nproc != 2

- name: set forbidden driver names
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regex: '^  "ForbiddenDriverNames": "",'
    line: '  "ForbiddenDriverNames": "{{ forbidden_driver_names }}",'

- name: set UDP ports
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regex: '^  "UDPPort": '
    line: '  "UDPPort": {{ udp_port_prefix }}00,'

- name: set TCP ports
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regex: '^  "TCPPort": '
    line: '  "TCPPort": {{ tcp_port_prefix }}00,'

- name: Set admin chat password if not set
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regexp: '^  "AdminPassword": "",'
    line: '  "AdminPassword": "{{ admin_chat_password }}",'

- name: Set UDP Plugin Local Port
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regexp: '^  "UDPPluginLocalPort": '
    line: '  "UDPPluginLocalPort": {{ plugin_udp_local_port_prefix }}000,'

- name: Set UDP Plugin Address
  ansible.builtin.lineinfile:
    dest: "{{ acmanagerStorePath }}/server_options.json"
    regexp: '^  "UDPPluginAddress": '
    line: '  "UDPPluginAddress": "{{ plugin_udp_address }}:{{ plugin_udp_port_prefix }}000",'
