# update acsm
---

- name: add helper script for version tracking
  ansible.builtin.template:
    src: get_version.sh.j2
    dest: "{{ acmanager_path }}/get_version.sh"
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0740'

- name: run script to get installed version of acsm
  ansible.builtin.command: '{{ acmanager_path }}/get_version.sh'
  register: acsm_version
  when: acsm_zip_x86.changed or acsm_zip_arm32.changed

- name: output of version script
  ansible.builtin.debug:
    msg: 'Current version installed is: {{ acsm_version.stdout }}'
  when: verbose and (acsm_zip_x86.changed or acsm_zip_arm32.changed)

- name: backup installed verison before upgrading
  import_tasks: backup.yml
  when: acsm_zip_x86.changed or acsm_zip_arm32.changed

- name: install newer AC Server Manager x86
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ acmanager_path }}"
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0755'
  with_fileglob: "{{ acmanagerZip }}"
  when: acsm_zip_x86.changed and ansible_architecture == 'x86_64'

- name: install newer AC Server Manager arm32
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ acmanager_path }}"
    owner: "{{ assetto_user }}"
    group: "{{ assetto_group }}"
    mode: '0755'
  with_fileglob: "{{ acmanagerZipArm32 }}"
  when: acsm_zip_arm32.changed and ansible_architecture == 'arm32'
